version: "3.0"

services:
  network-animator-render:
    build: ./
    container_name: network-animator-render
    volumes:
      - ./dist/:/app/dist/
      - ./examples/:/app/examples/
      - ./output/:/app/output/
    shm_size: 1G
    entrypoint: "timecut examples/ice-network.svg --start 5 --duration=450 --viewport=3840,2160 --fps=60 --pipe-mode --launch-arguments='--no-sandbox --disable-setuid-sandbox --allow-file-access-from-files' --pix-fmt=yuv420p --output=output/out.mp4"

